from app.db_adapter import _rewrite_sql, is_postgres_dsn, normalize_database_url


def test_postgres_dsn_detection_prefers_database_url(monkeypatch):
    monkeypatch.setenv("DATABASE_URL", "postgresql://user:pass@host/db")
    assert normalize_database_url("founderpilot.sqlite3").startswith("postgresql://")
    assert is_postgres_dsn("founderpilot.sqlite3")


def test_postgres_placeholder_and_returning_rewrite(monkeypatch):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    sql, params = _rewrite_sql("INSERT INTO ai_requests (telegram_id, mode) VALUES (?, ?)", (1, "chat"))
    assert "VALUES ($1, $2)" in sql
    assert sql.rstrip().endswith("RETURNING id")
    assert params == (1, "chat")


def test_postgres_pragmas_are_rewritten():
    sql, params = _rewrite_sql("PRAGMA table_info(users)", ())
    assert "information_schema.columns" in sql
    assert params == ("users",)


def test_sqlite_autoincrement_ddl_rewrite():
    sql, _ = _rewrite_sql("CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)", ())
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
